### ISSUE TITLE
Blank Single Task View & Reports After Update (Feng Office 3.7.0.5 -> 3.8.5.8)

### ISSUE THREAD

**Issue by nathaneyre** [fengoffice/fengoffice#45]
After updating Feng Office from 3.7.0.5 to 3.8.5.8 using the documented upgrade steps when selecting a workspace, clicking on tasks, and clicking an individual task the page is blank.

I found to remedy this on my system I had to add a field to the <table_prefix>project_tasks table:
`move_direction_non_working_days` varchar(255) DEFAULT 'advance'.

**Comment by NathanEyre** [comment]
I also found I was receiving blank reports which I was able to remedy this on my system by adding add a field to the <table_prefix>reports table:
`function_url` varchar(255) DEFAULT ''

I'm guessing somewhere along the line a migration wasn't preformed correctly on my system.
